### ISSUE TITLE
Correct dimension specifiers in subset elements

### ISSUE THREAD

**Issue by anchal-physics** [ProjectTorreyPines/SOLPS2IMAS.jl#16]
## Nodes, Edges, Cells are elongated in toroidal direction

Thus dimensions mentioned in the comments here:
https://github.com/ProjectTorreyPines/SOLPS2IMAS.jl/blob/f56e79e51c0186c1bf60e6308922932ccd22fa27/src/SOLPS2IMAS.jl#L966
are wrong. Nodes are 1D, Edges are 2D, and cells are 3D.

Reference to 4D objects should be removed. They are not used anywhere anyways:
https://github.com/ProjectTorreyPines/SOLPS2IMAS.jl/blob/f56e79e51c0186c1bf60e6308922932ccd22fa27/src/SOLPS2IMAS.jl#L969

## Hard-coded dimension numbers need to increment by 1

While adding elements to subset, dimension is given as an argument to add_subset_element! function. This has been hard coded to previous convention. These all need to be changed.
Example:
https://github.com/ProjectTorreyPines/SOLPS2IMAS.jl/blob/f56e79e51c0186c1bf60e6308922932ccd22fa27/src/SOLPS2IMAS.jl#L1051

## Task list

- [x] Correct dimension comments on `/src/SOLPS2IMAS.jl#L966-L968`
- [x] Remove reference to 4D object (currently marked as 3D) `/src/SOLPS2IMAS.jl#L969`
- [x] Find all uses of add_subset_element! and correct the dimension argument provided there.
- [x] Find all functions functions that use subset.element[:].object[1].dimension and fix them.
- [x] GGDUtils has some functions that use subset.element[:].object[1].dimension, fix all such uses.
